-- local prettier = require("prettier")
--
-- prettier.setup({
-- 	cli_options = {
-- 		tab_width = 4,
-- 	},
--
-- 	bin = "prettier", -- or `'prettierd'` (v0.23.3+)
-- 	filetypes = {
-- 		"css",
-- 		"graphql",
-- 		"html",
-- 		"javascript",
-- 		"javascriptreact",
-- 		"json",
-- 		"less",
-- 		"markdown",
-- 		"scss",
-- 		"typescript",
-- 		"typescriptreact",
-- 		"yaml",
-- 	},
-- })
